language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: OeHUk6ngDhsh+k6raRjDBuWjWJb3MEV9bqZqTUN/xTacpM/DgXs55qnm8LXdDfZhDpdwNUCFBgUwWrNgjPx0NJDYO1H97VIUlGyfqC/3M/JakHqjkG9t3CUSdAmkXsrH3AypPSAvYc6JRgs5MJUn1cONc53fprqyKaaaqqvsEGn3WdazQWZCoTb+//rY2iSAQOncLIEiDTVPZ3ufzQkUyT/5ZTc3Fo4aPBsYWVqiGQyDLwS5/oEcx2898CCVcX4G+D/1UBcbKs37Heo9iRIRlz1hTDZUCdne0oegIsVFbeOJRMX7E0X3KBDseT02tetpWeLu3ogNgCrhM463+/QqPWJCNgLsyXJ+0ohu3rQ/v98ujM9fBouAA8qxzJPu7qbIK0agdtDRD6If54mVFgZupE1rs4E2NltqumDCRUATDaM64C8j2UyeV+VlcR7Lp7VoNjg1hLQOHco8Tb9brM8BUiyObYxH/UKF0urSJmQ5Gdo71dWp9PW6KRgMAp4CHb1kbC5olNBfGOm82fsI/Gv5wUnHKroK43ibBi0blq1mmP/Gnpf5Lt7O+rZzo7aam7fMS7ZZScjSNrp/37+Q7bWcAm3noXCHiBqcyRs18DD0cmZAVD9I0TbwIlYUTCN68Kmx9iiCfdpW7kdzAJga12Zmfiy3wPM3a9wUxON3nzVKEac=
  app: pacific-shore-78581
  on:
    repo: GrimmOutlook/travel-game-plan-api
