language: node_js
node_js: node
before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
env:
  matrix:
  - CI=true
  - secure: OfsZWvVxB+MdeIrprZmKz9QrwFpfbdg+HSYh3xmYi4MqycY/6hO+Rm8bRwBlTXtmmmKzHWVaye4aiOxzXKrINNZP5/niVF7gt5eSbfwnR+q+mCHO9HaUTqmnW5uHRqk60HeRu83ti0a3RMhmiT0jERPP3eUEuXHJ6xun/iajjUR07GagoAfEXeIeDISjuE5+Cc3DrB87sB9GMzMZppyQ7X/y3kMHct+qNJWVErYciYnIEh5gZY5uIBrwv3sxV0bJBtJ47ohdHO1w2mCgtoC9u3UQzCgPRZHkYO2TgammUFNnPtvRYXiuroaBzY1sDM+80SP8ox3d0XAW0u9mcjyrI/OsqsLBa3K8YTOZpSzOFmXR6DGfdQ2JI6uQXgBUswe1r7DX0LemZn7cuZiosefE3uXkLLsU4PO8niSj2V0sk0JoWcl7kEKzeEII3QntTaE1d3ZIKbS50yvuZ6snQCJfAoK6lRAZyE/5NZeH1dkPk35wecdMmFOO9hqxRXwIQqcXJRJEPYKIlwp3bVRN8hBzjhmySoTmbBQSLljUl0+lDIJPMO0/l1lt0WbTnnOhncQ9hltQi3r1aVkJXkQK4AQ1pB46vWApuvZH9RAl7e3d8LGtGcdGp+HBFuGfkPJmSrjYG1bHLDjc0C488RwtuCWO5W/RZyzh0al+aC4nEHfWsS4=
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: xOTRCoXgHpw2HR6NjoUi+gT3m7HJR/7sJlB3KHDDvzTYLQY3Q3Dds1cE972CJ1enD9yJVCid5x5PCFOCxkgCIEN4v07E99SVaJcPAdE+79r/2Dik4YhaT12OOWo1z81atrkmXHOMWIbbSP5B/zJibFjg+Ji0n4LB2AfsyR55Ly0cLkKInO/8MO9V+V9HKHGb5wnqRrCS3wfJS0WFoSKrQixsQVfmzD/P455x05YXQSOFSsOLXqZdANhEcPCw5pvz7g6uztzmDt2X12GakoJd5FKz5kAoFSSslN2Q3gKvvbLJ9CDsxT/xP8f9rQg9yESdpOajnd2Mg1garw5v7UgL0gSgvIPZDfkDFD9Kw4OZFlIdjlVpimw6a5qXHwXzBCMVIDebmfrm8LN4bQHhENpa9JNDyYJcGpMT4LQqSqGmlpQQzQN/EOVu/3ob4UkgQ2CBd9kRDWRim8U+haIpubzFmfrNT8E/kN7HVl1nbB+QGnQp6RHgSV3x1YPvQZTmRBI7prtcX9b5vGz6LKNubKeYuU3QV5XEDUkI/Ues3euwZz3S8nt5rgUbqPXtmCJC9CzGnKoishcDU8nOUtH6J3CnD5F7iH0CmrlbFWKMGmOn9qEV55GTmZr997g1mmlCoNXql6uh9BriXz1ooaDlqndWGdHOLU+vZJqP8vaQZbOjVOE=
  app: travel-game-plan
  on:
    repo: GrimmOutlook/travel-game-plan-api
